version: '3.2'

networks:
  local:

services:
  nginx:
    container_name: mfp-map
    restart: always    
    image: nginx:latest  # Use the official nginx image from Docker Hub
    ports:
      - "8082:80"
    volumes:
      - ../dist/index.html:/usr/share/nginx/html/mpf/index.html
      - ../dist/static:/usr/share/nginx/html/mpf/static
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro  # Mount the .htpasswd file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount a custom nginx configuration file
